version: "3.8"

services:
  client:
    image: node
    stdin_open: true
    working_dir: /home/node/app
    ports:
      - 3000:3000
    volumes:
      - ./client:/home/node/app
      - /client/node_modules
    command: "yarn start"

  api:
    image: node
    stdin_open: true
    working_dir: /home/node/app
    ports:
      - 9000:9000
    volumes:
      - ./api:/home/node/app
      - /api/node_modules
    command: "yarn start"
